### ISSUE TITLE
Exceptions raised when using SDK

### ISSUE THREAD

**Issue by alexkhantreras** [MethodFi/method-python#21]
Hi - encountering some errors while running through a simple example flow. On `from method import Method`, actually, before any calls are made. Running Python 3.8 and 3.11. 

I don't _think_ it's my set up - a straight forward `pip install method-python` in a virtual environment. If I make the below changes in site-packages post install the SDK works and I can make successful API calls. But I could be off-base.

Thanks for any time.

### 1. A couple of illegal annotation syntax errors
```
Traceback (most recent call last):
  File "start_script.py", line 1, in <module>
    from method import Method
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/__init__.py", line 1, in <module>
    from method.method import Method
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/method.py", line 2, in <module>
    from method.resources.Account import AccountResource
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/resources/__init__.py", line 7, in <module>
    from method.resources.Merchant import Merchant, MerchantResource
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/resources/Merchant.py", line 54
    'provider_id.plaid': Optional[str]
    ^
SyntaxError: illegal target for annotation
```

One in `resources/Account`

https://github.com/MethodFi/method-python/blob/654cc8ab05f5e1ca8884aae2fcb3d225b6839dc7/method/resources/Account.py#L395-L405

and another in `resources/Merchant`

https://github.com/MethodFi/method-python/blob/654cc8ab05f5e1ca8884aae2fcb3d225b6839dc7/method/resources/Merchant.py#L51-L55

[I think that illegal identifiers are only allowed in the functional definition of TypedDicts.](https://docs.python.org/3/library/typing.html#typing.TypedDict)

### 2. A couple of `TypeErrors`
```
Traceback (most recent call last):
  File "start_script.py", line 1, in <module>
    from method import Method
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/__init__.py", line 1, in <module>
    from method.method import Method
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/method.py", line 2, in <module>
    from method.resources.Account import AccountResource
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/resources/__init__.py", line 2, in <module>
    from method.resources.Account import Account, AccountResource
  File "/Users/alex/Documents/MethodTakeHome/lib/python3.8/site-packages/method/resources/Account.py", line 429, in <module>
    class AccountCreateBulkSensitiveResponse(TypedDict):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 1749, in __new__
    anns = {n: _type_check(tp, msg) for n, tp in anns.items()}
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 1749, in <dictcomp>
    anns = {n: _type_check(tp, msg) for n, tp in anns.items()}
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: TypedDict('Name', {f0: t0, f1: t1, ...}); each t must be a type Got [<class 'method.resources.Account.AccountSensitive'>].
```

In `resources/Account`, lines 415

https://github.com/MethodFi/method-python/blob/654cc8ab05f5e1ca8884aae2fcb3d225b6839dc7/method/resources/Account.py#L415

 and 429

https://github.com/MethodFi/method-python/blob/654cc8ab05f5e1ca8884aae2fcb3d225b6839dc7/method/resources/Account.py#L429

Probably missing the preceding `List` to make them `List[...]` if semantics of the type are plural, otherwise the brackets are not needed.

### 3. Small typo
Line 505 calls `create_with_subpath(...` while other calls are `create_with_sub_path(...`

https://github.com/MethodFi/method-python/blob/654cc8ab05f5e1ca8884aae2fcb3d225b6839dc7/method/resources/Account.py#L504-L511

**Comment by ossiggy** [comment]
@alexkhantreras thank you so much for bringing these to our attention! [I just submitted a PR to fix these](https://github.com/MethodFi/method-python/pull/22).  If you would like to take a look and make sure it mimics what you were doing locally, that would be appreciated!
